# Generated by Django 3.0 on 2019-12-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webalta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='picture',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='picture',
            field=models.CharField(max_length=1000),
        ),
    ]
