# Generated by Django 3.0 on 2019-12-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webalta', '0002_auto_20191210_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=1000)),
                ('artikel', models.CharField(max_length=10000)),
                ('picture', models.CharField(max_length=1000)),
                ('tanggal', models.DateField()),
            ],
        ),
    ]
